// ─── Dummy Data Store ───
// All data lives in memory. CRUD operations mutate these arrays.

// ─── USERS ───
export const dummyUsers = [
    {
        id: 1,
        row_index: 1,
        username: 'admin',
        password: 'admin123',
        name: 'Admin User',
        administrate: true,
        create_indent: true,
        all_indent: true,
        create_po: true,
        indent_approval_view: true,
        indent_approval_action: true,
        update_vendor_view: true,
        update_vendor_action: true,
        three_party_approval_view: true,
        three_party_approval_action: true,
        receive_item_view: true,
        receive_item_action: true,
        store_out_approval_view: true,
        store_out_approval_action: true,
        quotation: true,
        pending_indents_view: true,
        orders_view: true,
        po_master: true,
        get_purchase: true,
        dashboard: true,
        inventory: true,
        setting: true,
    },
    {
        id: 2,
        row_index: 2,
        username: 'viewer',
        password: 'viewer123',
        name: 'Viewer User',
        administrate: false,
        create_indent: true,
        all_indent: true,
        create_po: false,
        indent_approval_view: true,
        indent_approval_action: false,
        update_vendor_view: true,
        update_vendor_action: false,
        three_party_approval_view: true,
        three_party_approval_action: false,
        receive_item_view: true,
        receive_item_action: false,
        store_out_approval_view: true,
        store_out_approval_action: false,
        quotation: true,
        pending_indents_view: true,
        orders_view: true,
        po_master: true,
        get_purchase: true,
        dashboard: true,
        inventory: true,
        setting: false,
    },
    {
        id: 3,
        row_index: 3,
        username: 'manager',
        password: 'manager123',
        name: 'Manager User',
        administrate: true,
        create_indent: true,
        all_indent: true,
        create_po: true,
        indent_approval_view: true,
        indent_approval_action: true,
        update_vendor_view: true,
        update_vendor_action: true,
        three_party_approval_view: true,
        three_party_approval_action: true,
        receive_item_view: true,
        receive_item_action: true,
        store_out_approval_view: true,
        store_out_approval_action: true,
        quotation: true,
        pending_indents_view: true,
        orders_view: true,
        po_master: true,
        get_purchase: true,
        dashboard: true,
        inventory: true,
        setting: true,
    },
];

// ─── INDENT ───
export const dummyIndents: any[] = [
    {
        id: 1,
        created_at: '2025-01-15 10:00:00',
        timestamp: '2025-01-15 10:00:00',
        indent_number: 'SI-0001',
        indenter_name: 'Rahul Kumar',
        department: 'Maintenance',
        area_of_use: 'Workshop',
        group_head: 'Electrical',
        product_name: 'LED Bulb 20W',
        quantity: 50,
        uom: 'Pcs',
        specifications: 'Philips brand, cool white',
        indent_approved_by: 'Manager',
        indent_type: 'Purchase',
        attachment: '',
        planned_1: '2025-01-16',
        actual_1: '2025-01-16',
        time_delay_1: '0',
        vendor_type: 'Direct',
        approved_quantity: 50,
        planned_2: '2025-01-17',
        actual_2: '2025-01-17',
        time_delay_2: '0',
        vendor_name_1: 'Philips India Ltd',
        rate_1: 120,
        payment_term_1: 'Net 30',
        vendor_name_2: 'Havells Ltd',
        rate_2: 135,
        payment_term_2: 'Net 45',
        vendor_name_3: '',
        rate_3: 0,
        payment_term_3: '',
        comparison_sheet: '',
        planned_3: '',
        actual_3: '',
        time_delay_3: '',
        approved_vendor_name: 'Philips India Ltd',
        approved_rate: 120,
        approved_payment_term: 'Net 30',
        approved_date: '2025-01-18',
        planned_4: '2025-01-19',
        actual_4: '2025-01-19',
        time_delay_4: '0',
        po_number: 'PO-2025-001',
        po_copy: '',
        planned_5: '2025-01-22',
        actual_5: '2025-01-22',
        time_delay_5: '0',
        receive_status: 'Received',
        planned_6: '',
        actual_6: '',
        time_delay_6: '',
        issue_approved_by: '',
        issue_status: '',
        issued_quantity: 0,
        planned_7: '',
        actual_7: '',
        time_delay_7: '',
        bill_status: '',
        bill_number: '',
        qty: 0,
        lead_time_to_lift_material: '',
        type_of_bill: '',
        bill_amount: 0,
        discount_amount: 0,
        payment_type: '',
        advance_amount_if_any: 0,
        photo_of_bill: '',
        rate: 120,
    },
    {
        id: 2,
        created_at: '2025-01-20 11:00:00',
        timestamp: '2025-01-20 11:00:00',
        indent_number: 'SI-0002',
        indenter_name: 'Suresh Patel',
        department: 'Production',
        area_of_use: 'Factory Floor',
        group_head: 'Mechanical',
        product_name: 'Bearing 6205',
        quantity: 100,
        uom: 'Pcs',
        specifications: 'SKF make, sealed type',
        indent_approved_by: 'Manager',
        indent_type: 'Purchase',
        attachment: '',
        planned_1: '2025-01-21',
        actual_1: '2025-01-21',
        time_delay_1: '0',
        vendor_type: 'Three Party',
        approved_quantity: 100,
        planned_2: '2025-01-22',
        actual_2: '2025-01-22',
        time_delay_2: '0',
        vendor_name_1: 'SKF India',
        rate_1: 250,
        payment_term_1: 'Net 30',
        vendor_name_2: 'NTN Bearing',
        rate_2: 230,
        payment_term_2: 'Net 30',
        vendor_name_3: 'FAG Bearings',
        rate_3: 245,
        payment_term_3: 'Net 45',
        comparison_sheet: '',
        planned_3: '2025-01-23',
        actual_3: '2025-01-23',
        time_delay_3: '0',
        approved_vendor_name: 'NTN Bearing',
        approved_rate: 230,
        approved_payment_term: 'Net 30',
        approved_date: '2025-01-24',
        planned_4: '2025-01-25',
        actual_4: '2025-01-25',
        time_delay_4: '0',
        po_number: 'PO-2025-002',
        po_copy: '',
        planned_5: '2025-01-28',
        actual_5: '2025-01-28',
        time_delay_5: '0',
        receive_status: 'Received',
        planned_6: '',
        actual_6: '',
        time_delay_6: '',
        issue_approved_by: '',
        issue_status: '',
        issued_quantity: 0,
        planned_7: '',
        actual_7: '',
        time_delay_7: '',
        bill_status: '',
        bill_number: '',
        qty: 0,
        lead_time_to_lift_material: '',
        type_of_bill: '',
        bill_amount: 0,
        discount_amount: 0,
        payment_type: '',
        advance_amount_if_any: 0,
        photo_of_bill: '',
        rate: 230,
    },
    {
        id: 3,
        created_at: '2025-02-01 09:00:00',
        timestamp: '2025-02-01 09:00:00',
        indent_number: 'SI-0003',
        indenter_name: 'Amit Sharma',
        department: 'Electrical',
        area_of_use: 'Control Room',
        group_head: 'Electrical',
        product_name: 'MCB 32A',
        quantity: 20,
        uom: 'Pcs',
        specifications: 'Schneider, C-curve',
        indent_approved_by: 'Admin',
        indent_type: 'Purchase',
        attachment: '',
        planned_1: '2025-02-02',
        actual_1: '2025-02-02',
        time_delay_1: '0',
        vendor_type: 'Three Party',
        approved_quantity: 20,
        planned_2: '2025-02-03',
        actual_2: '',
        time_delay_2: '',
        vendor_name_1: 'Schneider Electric',
        rate_1: 450,
        payment_term_1: 'Net 30',
        vendor_name_2: '',
        rate_2: 0,
        payment_term_2: '',
        vendor_name_3: '',
        rate_3: 0,
        payment_term_3: '',
        comparison_sheet: '',
        planned_3: '',
        actual_3: '',
        time_delay_3: '',
        approved_vendor_name: 'Schneider Electric',
        approved_rate: 450,
        approved_payment_term: 'Net 30',
        approved_date: '2025-02-04',
        planned_4: '2025-02-05',
        actual_4: '2025-02-05',
        time_delay_4: '0',
        po_number: 'PO-2025-003',
        po_copy: '',
        planned_5: '',
        actual_5: '',
        time_delay_5: '',
        receive_status: '',
        planned_6: '',
        actual_6: '',
        time_delay_6: '',
        issue_approved_by: '',
        issue_status: '',
        issued_quantity: 0,
        planned_7: '',
        actual_7: '',
        time_delay_7: '',
        bill_status: '',
        bill_number: '',
        qty: 0,
        lead_time_to_lift_material: '',
        type_of_bill: '',
        bill_amount: 0,
        discount_amount: 0,
        payment_type: '',
        advance_amount_if_any: 0,
        photo_of_bill: '',
        rate: 450,
    },
    {
        id: 4,
        created_at: '2025-02-10 14:00:00',
        timestamp: '2025-02-10 14:00:00',
        indent_number: 'SI-0004',
        indenter_name: 'Vijay Singh',
        department: 'Maintenance',
        area_of_use: 'Boiler Room',
        group_head: 'Piping',
        product_name: 'GI Pipe 1 inch',
        quantity: 30,
        uom: 'Meter',
        specifications: 'ISI marked, schedule 40',
        indent_approved_by: 'Manager',
        indent_type: 'Purchase',
        attachment: '',
        planned_1: '2025-02-11',
        actual_1: '2025-02-11',
        time_delay_1: '0',
        vendor_type: 'Regular',
        approved_quantity: 30,
        planned_2: '',
        actual_2: '',
        time_delay_2: '',
        vendor_name_1: '',
        rate_1: 0,
        payment_term_1: '',
        vendor_name_2: '',
        rate_2: 0,
        payment_term_2: '',
        vendor_name_3: '',
        rate_3: 0,
        payment_term_3: '',
        comparison_sheet: '',
        planned_3: '',
        actual_3: '',
        time_delay_3: '',
        approved_vendor_name: '',
        approved_rate: 0,
        approved_payment_term: '',
        approved_date: '',
        planned_4: '',
        actual_4: '',
        time_delay_4: '',
        po_number: '',
        po_copy: '',
        planned_5: '',
        actual_5: '',
        time_delay_5: '',
        receive_status: '',
        planned_6: '',
        actual_6: '',
        time_delay_6: '',
        issue_approved_by: '',
        issue_status: '',
        issued_quantity: 0,
        planned_7: '',
        actual_7: '',
        time_delay_7: '',
        bill_status: '',
        bill_number: '',
        qty: 0,
        lead_time_to_lift_material: '',
        type_of_bill: '',
        bill_amount: 0,
        discount_amount: 0,
        payment_type: '',
        advance_amount_if_any: 0,
        photo_of_bill: '',
        rate: 0,
    },
    {
        id: 5,
        created_at: '2025-02-15 08:30:00',
        timestamp: '2025-02-15 08:30:00',
        indent_number: 'SI-0005',
        indenter_name: 'Rahul Kumar',
        department: 'Production',
        area_of_use: 'Assembly Line',
        group_head: 'Consumables',
        product_name: 'Welding Rod 3.15mm',
        quantity: 200,
        uom: 'Kgs',
        specifications: 'ESAB OK 46.00',
        indent_approved_by: 'Admin',
        indent_type: 'Store Out',
        attachment: '',
        planned_1: '2025-02-16',
        actual_1: '2025-02-16',
        time_delay_1: '0',
        vendor_type: '',
        approved_quantity: 200,
        planned_2: '',
        actual_2: '',
        time_delay_2: '',
        vendor_name_1: '',
        rate_1: 0,
        payment_term_1: '',
        vendor_name_2: '',
        rate_2: 0,
        payment_term_2: '',
        vendor_name_3: '',
        rate_3: 0,
        payment_term_3: '',
        comparison_sheet: '',
        planned_3: '',
        actual_3: '',
        time_delay_3: '',
        approved_vendor_name: '',
        approved_rate: 0,
        approved_payment_term: '',
        approved_date: '',
        planned_4: '',
        actual_4: '',
        time_delay_4: '',
        po_number: '',
        po_copy: '',
        planned_5: '',
        actual_5: '',
        time_delay_5: '',
        receive_status: '',
        planned_6: '2025-02-17',
        actual_6: '',
        time_delay_6: '',
        issue_approved_by: '',
        issue_status: '',
        issued_quantity: 0,
        planned_7: '',
        actual_7: '',
        time_delay_7: '',
        bill_status: '',
        bill_number: '',
        qty: 0,
        lead_time_to_lift_material: '',
        type_of_bill: '',
        bill_amount: 0,
        discount_amount: 0,
        payment_type: '',
        advance_amount_if_any: 0,
        photo_of_bill: '',
        rate: 0,
    },
    {
        id: 6,
        created_at: '2025-03-01 10:00:00',
        timestamp: '2025-03-01 10:00:00',
        indent_number: 'SI-0006',
        indenter_name: 'Suresh Patel',
        department: 'Electrical',
        area_of_use: 'Panel Room',
        group_head: 'Electrical',
        product_name: 'Cable 4 Sq mm',
        quantity: 500,
        uom: 'Meter',
        specifications: 'Polycab, FRLS, copper',
        indent_approved_by: 'Manager',
        indent_type: 'Purchase',
        attachment: '',
        planned_1: '2025-03-02',
        actual_1: '2025-03-02',
        time_delay_1: '0',
        vendor_type: 'Direct',
        approved_quantity: 500,
        planned_2: '2025-03-03',
        actual_2: '2025-03-03',
        time_delay_2: '0',
        vendor_name_1: 'Polycab India',
        rate_1: 45,
        payment_term_1: 'Net 30',
        vendor_name_2: 'Finolex Cables',
        rate_2: 48,
        payment_term_2: 'Net 30',
        vendor_name_3: '',
        rate_3: 0,
        payment_term_3: '',
        comparison_sheet: '',
        planned_3: '',
        actual_3: '',
        time_delay_3: '',
        approved_vendor_name: 'Polycab India',
        approved_rate: 45,
        approved_payment_term: 'Net 30',
        approved_date: '2025-03-04',
        planned_4: '2025-03-05',
        actual_4: '2025-03-05',
        time_delay_4: '0',
        po_number: 'PO-2025-004',
        po_copy: '',
        planned_5: '2025-03-08',
        actual_5: '2025-03-08',
        time_delay_5: '0',
        receive_status: 'Received',
        planned_6: '',
        actual_6: '',
        time_delay_6: '',
        issue_approved_by: '',
        issue_status: 'Issued',
        issued_quantity: 500,
        planned_7: '',
        actual_7: '',
        time_delay_7: '',
        bill_status: '',
        bill_number: '',
        qty: 0,
        lead_time_to_lift_material: '',
        type_of_bill: '',
        bill_amount: 0,
        discount_amount: 0,
        payment_type: '',
        advance_amount_if_any: 0,
        photo_of_bill: '',
        rate: 45,
    },
    {
        id: 7,
        created_at: '2025-03-10 11:30:00',
        timestamp: '2025-03-10 11:30:00',
        indent_number: 'SI-0007',
        indenter_name: 'Amit Sharma',
        department: 'Maintenance',
        area_of_use: 'Workshop',
        group_head: 'Tools',
        product_name: 'Drill Bit Set HSS',
        quantity: 5,
        uom: 'Set',
        specifications: 'Bosch, 1mm to 13mm',
        indent_approved_by: 'Manager',
        indent_type: 'Purchase',
        attachment: '',
        planned_1: '2025-03-11',
        actual_1: '2025-03-11',
        time_delay_1: '0',
        vendor_type: 'Direct',
        approved_quantity: 5,
        planned_2: '2025-03-12',
        actual_2: '2025-03-12',
        time_delay_2: '0',
        vendor_name_1: 'Bosch Power Tools',
        rate_1: 1200,
        payment_term_1: 'Advance',
        vendor_name_2: '',
        rate_2: 0,
        payment_term_2: '',
        vendor_name_3: '',
        rate_3: 0,
        payment_term_3: '',
        comparison_sheet: '',
        planned_3: '',
        actual_3: '',
        time_delay_3: '',
        approved_vendor_name: 'Bosch Power Tools',
        approved_rate: 1200,
        approved_payment_term: 'Advance',
        approved_date: '2025-03-13',
        planned_4: '2025-03-14',
        actual_4: '',
        time_delay_4: '',
        po_number: '',
        po_copy: '',
        planned_5: '',
        actual_5: '',
        time_delay_5: '',
        receive_status: '',
        planned_6: '',
        actual_6: '',
        time_delay_6: '',
        issue_approved_by: '',
        issue_status: '',
        issued_quantity: 0,
        planned_7: '',
        actual_7: '',
        time_delay_7: '',
        bill_status: '',
        bill_number: '',
        qty: 0,
        lead_time_to_lift_material: '',
        type_of_bill: '',
        bill_amount: 0,
        discount_amount: 0,
        payment_type: '',
        advance_amount_if_any: 0,
        photo_of_bill: '',
        rate: 1200,
    },
];

// ─── RECEIVED ───
export const dummyReceived: any[] = [
    {
        id: 1,
        timestamp: '2025-01-22 14:00:00',
        indent_number: 'SI-0001',
        po_date: '2025-01-19',
        po_number: 'PO-2025-001',
        vendor: 'Philips India Ltd',
        received_status: 'Received',
        received_quantity: 50,
        uom: 'Pcs',
        photo_of_product: '',
        warranty_status: 'No Warranty',
        end_date: '',
        bill_status: '',
        bill_number: '',
        bill_amount: 0,
        photo_of_bill: '',
        any_transportations: 'No',
        transporter_name: '',
        transporting_amount: 0,
    },
    {
        id: 2,
        timestamp: '2025-01-28 15:00:00',
        indent_number: 'SI-0002',
        po_date: '2025-01-25',
        po_number: 'PO-2025-002',
        vendor: 'NTN Bearing',
        received_status: 'Received',
        received_quantity: 60,
        uom: 'Pcs',
        photo_of_product: '',
        warranty_status: '1 Year',
        end_date: '2026-01-28',
        bill_status: '',
        bill_number: '',
        bill_amount: 0,
        photo_of_bill: '',
        any_transportations: 'Yes',
        transporter_name: 'Blue Dart',
        transporting_amount: 500,
    },
    {
        id: 3,
        timestamp: '2025-01-30 10:00:00',
        indent_number: 'SI-0002',
        po_date: '2025-01-25',
        po_number: 'PO-2025-002',
        vendor: 'NTN Bearing',
        received_status: 'Received',
        received_quantity: 40,
        uom: 'Pcs',
        photo_of_product: '',
        warranty_status: '1 Year',
        end_date: '2026-01-30',
        bill_status: '',
        bill_number: '',
        bill_amount: 0,
        photo_of_bill: '',
        any_transportations: 'No',
        transporter_name: '',
        transporting_amount: 0,
    },
    {
        id: 4,
        timestamp: '2025-03-08 11:00:00',
        indent_number: 'SI-0006',
        po_date: '2025-03-05',
        po_number: 'PO-2025-004',
        vendor: 'Polycab India',
        received_status: 'Received',
        received_quantity: 500,
        uom: 'Meter',
        photo_of_product: '',
        warranty_status: 'No Warranty',
        end_date: '',
        bill_status: '',
        bill_number: '',
        bill_amount: 0,
        photo_of_bill: '',
        any_transportations: 'Yes',
        transporter_name: 'DTDC',
        transporting_amount: 800,
    },
];

// ─── PO MASTER ───
export const dummyPoMaster: any[] = [
    {
        id: 1,
        timestamp: '2025-01-19 10:00:00',
        party_name: 'Philips India Ltd',
        po_number: 'PO-2025-001',
        quotation_number: 'Q-001',
        quotation_date: '2025-01-17',
        enquiry_number: 'ENQ-001',
        enquiry_date: '2025-01-15',
        internal_code: 'IC-001',
        product: 'LED Bulb 20W',
        description: 'Philips brand cool white LED',
        quantity: 50,
        unit: 'Pcs',
        rate: 120,
        gst_percent: 18,
        discount_percent: 0,
        amount: 7080,
        total_po_amount: 7080,
        prepared_by: 'Admin User',
        approved_by: 'Manager',
        pdf_url: '',
        term_1: 'Delivery within 7 days',
        term_2: 'Payment Net 30',
        term_3: '',
        term_4: '',
        term_5: '',
        term_6: '',
        term_7: '',
        term_8: '',
        term_9: '',
        term_10: '',
        email_send_status: false,
        created_at: '2025-01-19',
        updated_at: '2025-01-19',
    },
    {
        id: 2,
        timestamp: '2025-01-25 11:00:00',
        party_name: 'NTN Bearing',
        po_number: 'PO-2025-002',
        quotation_number: 'Q-002',
        quotation_date: '2025-01-22',
        enquiry_number: 'ENQ-002',
        enquiry_date: '2025-01-20',
        internal_code: 'IC-002',
        product: 'Bearing 6205',
        description: 'SKF make sealed type',
        quantity: 100,
        unit: 'Pcs',
        rate: 230,
        gst_percent: 18,
        discount_percent: 5,
        amount: 25783,
        total_po_amount: 25783,
        prepared_by: 'Admin User',
        approved_by: 'Manager',
        pdf_url: '',
        term_1: 'Delivery within 10 days',
        term_2: 'Payment Net 30',
        term_3: 'Quality as per sample',
        term_4: '',
        term_5: '',
        term_6: '',
        term_7: '',
        term_8: '',
        term_9: '',
        term_10: '',
        email_send_status: true,
        created_at: '2025-01-25',
        updated_at: '2025-01-25',
    },
    {
        id: 3,
        timestamp: '2025-02-05 09:00:00',
        party_name: 'Schneider Electric',
        po_number: 'PO-2025-003',
        quotation_number: 'Q-003',
        quotation_date: '2025-02-03',
        enquiry_number: 'ENQ-003',
        enquiry_date: '2025-02-01',
        internal_code: 'IC-003',
        product: 'MCB 32A',
        description: 'Schneider C-curve MCB',
        quantity: 20,
        unit: 'Pcs',
        rate: 450,
        gst_percent: 18,
        discount_percent: 0,
        amount: 10620,
        total_po_amount: 10620,
        prepared_by: 'Manager User',
        approved_by: 'Admin',
        pdf_url: '',
        term_1: 'Delivery within 5 days',
        term_2: 'Payment Net 30',
        term_3: '',
        term_4: '',
        term_5: '',
        term_6: '',
        term_7: '',
        term_8: '',
        term_9: '',
        term_10: '',
        email_send_status: false,
        created_at: '2025-02-05',
        updated_at: '2025-02-05',
    },
    {
        id: 4,
        timestamp: '2025-03-05 10:00:00',
        party_name: 'Polycab India',
        po_number: 'PO-2025-004',
        quotation_number: 'Q-004',
        quotation_date: '2025-03-03',
        enquiry_number: 'ENQ-004',
        enquiry_date: '2025-03-01',
        internal_code: 'IC-004',
        product: 'Cable 4 Sq mm',
        description: 'Polycab FRLS copper cable',
        quantity: 500,
        unit: 'Meter',
        rate: 45,
        gst_percent: 18,
        discount_percent: 2,
        amount: 24843,
        total_po_amount: 24843,
        prepared_by: 'Admin User',
        approved_by: 'Manager',
        pdf_url: '',
        term_1: 'Delivery within 3 days',
        term_2: 'Payment Net 30',
        term_3: 'ISI mark mandatory',
        term_4: '',
        term_5: '',
        term_6: '',
        term_7: '',
        term_8: '',
        term_9: '',
        term_10: '',
        email_send_status: true,
        created_at: '2025-03-05',
        updated_at: '2025-03-05',
    },
];

// ─── INVENTORY ───
export const dummyInventory: any[] = [
    {
        group_head: 'Electrical',
        item_name: 'LED Bulb 20W',
        uom: 'Pcs',
        max_level: 200,
        opening: 100,
        individual_rate: 120,
        indented: 50,
        approved: 50,
        purchase_quantity: 50,
        out_quantity: 10,
        current: 140,
        total_price: 16800,
        color_code: '',
    },
    {
        group_head: 'Mechanical',
        item_name: 'Bearing 6205',
        uom: 'Pcs',
        max_level: 500,
        opening: 200,
        individual_rate: 230,
        indented: 100,
        approved: 100,
        purchase_quantity: 100,
        out_quantity: 30,
        current: 270,
        total_price: 62100,
        color_code: '',
    },
    {
        group_head: 'Electrical',
        item_name: 'MCB 32A',
        uom: 'Pcs',
        max_level: 100,
        opening: 30,
        individual_rate: 450,
        indented: 20,
        approved: 20,
        purchase_quantity: 0,
        out_quantity: 5,
        current: 25,
        total_price: 11250,
        color_code: 'yellow',
    },
    {
        group_head: 'Electrical',
        item_name: 'Cable 4 Sq mm',
        uom: 'Meter',
        max_level: 1000,
        opening: 300,
        individual_rate: 45,
        indented: 500,
        approved: 500,
        purchase_quantity: 500,
        out_quantity: 500,
        current: 300,
        total_price: 13500,
        color_code: '',
    },
    {
        group_head: 'Consumables',
        item_name: 'Welding Rod 3.15mm',
        uom: 'Kgs',
        max_level: 500,
        opening: 150,
        individual_rate: 85,
        indented: 200,
        approved: 200,
        purchase_quantity: 0,
        out_quantity: 50,
        current: 100,
        total_price: 8500,
        color_code: 'red',
    },
];

// ─── MASTER DATA (company info, vendors) ───
export const dummyMasterData: any[] = [
    {
        id: 1,
        company_name: 'Botivate Services LLP',
        company_address:
            'Office No. 224, Shree Ram Business Park, Vidhan Sabha Rd, Block-I, Mowa, Raipur, Chhattisgarh 493111, Rajasthan',
        company_phone: '+91 9876543210',
        company_gstin: '08AABCU9603R1ZP',
        company_pan: 'AABCU9603R',
        billing_address:
            'Office No. 224, Shree Ram Business Park, Vidhan Sabha Rd, Block-I, Mowa, Raipur, Chhattisgarh 493111, Rajasthan',
        destination_address: '456, Factory Road, Phase-3, Jaipur, Rajasthan',
        default_terms: 'Delivery within 7 working days',
        vendor_name: 'Philips India Ltd',
        vendor_gstin: '08AABCT1234M1ZP',
        vendor_address: 'Philips Building, Sector 18, Gurgaon',
        vendor_email: 'orders@philips.in',
        payment_term: 'Net 30',
        department: 'Electrical',
        group_head: 'Electrical',
        item_name: 'LED Bulb 20W',
    },
    {
        id: 2,
        company_name: 'Botivate Services LLP',
        company_address:
            'Office No. 224, Shree Ram Business Park, Vidhan Sabha Rd, Block-I, Mowa, Raipur, Chhattisgarh 493111',
        company_phone: '+91 9876543210',
        company_gstin: '08AABCU9603R1ZP',
        company_pan: 'AABCU9603R',
        billing_address:
            'Office No. 224, Shree Ram Business Park, Vidhan Sabha Rd, Block-I, Mowa, Raipur, Chhattisgarh 493111',
        destination_address: '456, Factory Road, Phase-3, Jaipur',
        default_terms: 'Quality as per sample approved',
        vendor_name: 'NTN Bearing',
        vendor_gstin: '08AABCN5678P1ZQ',
        vendor_address: 'NTN Office, MG Road, Bangalore',
        vendor_email: 'sales@ntn.co.in',
        payment_term: 'Net 30',
        department: 'Production',
        group_head: 'Mechanical',
        item_name: 'Bearing 6205',
    },
    {
        id: 3,
        company_name: 'Botivate Services LLP',
        company_address:
            'Office No. 224, Shree Ram Business Park, Vidhan Sabha Rd, Block-I, Mowa, Raipur, Chhattisgarh 493111',
        company_phone: '+91 9876543210',
        company_gstin: '08AABCU9603R1ZP',
        company_pan: 'AABCU9603R',
        billing_address:
            'Office No. 224, Shree Ram Business Park, Vidhan Sabha Rd, Block-I, Mowa, Raipur, Chhattisgarh 493111',
        destination_address: '456, Factory Road, Phase-3, Jaipur',
        default_terms: 'Payment within 30 days of invoice',
        vendor_name: 'Schneider Electric',
        vendor_gstin: '08AABCS9012R1ZR',
        vendor_address: 'Schneider Tower, Whitefield, Bangalore',
        vendor_email: 'procurement@schneider.com',
        payment_term: 'Net 45',
        department: 'Maintenance',
        group_head: 'Piping',
        item_name: 'GI Pipe 1 inch',
    },
    {
        id: 4,
        company_name: 'Botivate Services LLP',
        company_address:
            'Office No. 224, Shree Ram Business Park, Vidhan Sabha Rd, Block-I, Mowa, Raipur, Chhattisgarh 493111',
        company_phone: '+91 9876543210',
        company_gstin: '08AABCU9603R1ZP',
        company_pan: 'AABCU9603R',
        billing_address:
            'Office No. 224, Shree Ram Business Park, Vidhan Sabha Rd, Block-I, Mowa, Raipur, Chhattisgarh 493111',
        destination_address: '456, Factory Road, Phase-3, Jaipur',
        default_terms: 'Subject to Jaipur jurisdiction',
        vendor_name: 'Polycab India',
        vendor_gstin: '08AABCP3456T1ZS',
        vendor_address: 'Polycab House, Andheri, Mumbai',
        vendor_email: 'sales@polycab.com',
        payment_term: 'Net 30',
        department: 'Electrical',
        group_head: 'Electrical',
        item_name: 'Cable 4 Sq mm',
    },
    {
        id: 5,
        company_name: 'Botivate Services LLP',
        company_address:
            'Office No. 224, Shree Ram Business Park, Vidhan Sabha Rd, Block-I, Mowa, Raipur, Chhattisgarh 493111',
        company_phone: '+91 9876543210',
        company_gstin: '08AABCU9603R1ZP',
        company_pan: 'AABCU9603R',
        billing_address:
            'Office No. 224, Shree Ram Business Park, Vidhan Sabha Rd, Block-I, Mowa, Raipur, Chhattisgarh 493111',
        destination_address: '456, Factory Road, Phase-3, Jaipur',
        default_terms: '',
        vendor_name: 'Bosch Power Tools',
        vendor_gstin: '08AABCB7890U1ZT',
        vendor_address: 'Bosch Center, Hosur Road, Bangalore',
        vendor_email: 'orders@bosch.in',
        payment_term: 'Advance',
        department: 'Maintenance',
        group_head: 'Tools',
        item_name: 'Drill Bit Set HSS',
    },
    {
        id: 6,
        company_name: 'Botivate Services LLP',
        company_address:
            'Office No. 224, Shree Ram Business Park, Vidhan Sabha Rd, Block-I, Mowa, Raipur, Chhattisgarh 493111',
        company_phone: '+91 9876543210',
        company_gstin: '08AABCU9603R1ZP',
        company_pan: 'AABCU9603R',
        billing_address:
            'Office No. 224, Shree Ram Business Park, Vidhan Sabha Rd, Block-I, Mowa, Raipur, Chhattisgarh 493111',
        destination_address: '456, Factory Road, Phase-3, Jaipur',
        default_terms: '',
        vendor_name: 'Havells Ltd',
        vendor_gstin: '08AABCH1234V1ZU',
        vendor_address: 'Havells Galaxy, Noida',
        vendor_email: 'b2b@havells.com',
        payment_term: 'Net 30',
        department: 'Electrical',
        group_head: 'Electrical',
        item_name: 'MCB 32A',
    },
    {
        id: 7,
        company_name: 'Botivate Services LLP',
        company_address:
            'Office No. 224, Shree Ram Business Park, Vidhan Sabha Rd, Block-I, Mowa, Raipur, Chhattisgarh 493111',
        company_phone: '+91 9876543210',
        company_gstin: '08AABCU9603R1ZP',
        company_pan: 'AABCU9603R',
        billing_address:
            'Office No. 224, Shree Ram Business Park, Vidhan Sabha Rd, Block-I, Mowa, Raipur, Chhattisgarh 493111',
        destination_address: '456, Factory Road, Phase-3, Jaipur',
        default_terms: '',
        vendor_name: 'SKF India',
        vendor_gstin: '08AABCS5678W1ZV',
        vendor_address: 'SKF House, Chinchwad, Pune',
        vendor_email: 'orders@skf.com',
        payment_term: 'Net 45',
        department: 'Production',
        group_head: 'Consumables',
        item_name: 'Welding Rod 3.15mm',
    },
    {
        id: 8,
        company_name: 'Botivate Services LLP',
        company_address:
            'Office No. 224, Shree Ram Business Park, Vidhan Sabha Rd, Block-I, Mowa, Raipur, Chhattisgarh 493111',
        company_phone: '+91 9876543210',
        company_gstin: '08AABCU9603R1ZP',
        company_pan: 'AABCU9603R',
        billing_address:
            'Office No. 224, Shree Ram Business Park, Vidhan Sabha Rd, Block-I, Mowa, Raipur, Chhattisgarh 493111',
        destination_address: '456, Factory Road, Phase-3, Jaipur',
        default_terms: '',
        vendor_name: 'FAG Bearings',
        vendor_gstin: '08AABCF9012X1ZW',
        vendor_address: 'Schaeffler India, Vadodara, Gujarat',
        vendor_email: 'sales@schaeffler.in',
        payment_term: 'Net 45',
        department: 'Production',
        group_head: 'Mechanical',
        item_name: 'Drill Bit Set HSS',
    },
    {
        id: 9,
        company_name: 'Botivate Services LLP',
        company_address:
            'Office No. 224, Shree Ram Business Park, Vidhan Sabha Rd, Block-I, Mowa, Raipur, Chhattisgarh 493111',
        company_phone: '+91 9876543210',
        company_gstin: '08AABCU9603R1ZP',
        company_pan: 'AABCU9603R',
        billing_address:
            'Office No. 224, Shree Ram Business Park, Vidhan Sabha Rd, Block-I, Mowa, Raipur, Chhattisgarh 493111',
        destination_address: '456, Factory Road, Phase-3, Jaipur',
        default_terms: '',
        vendor_name: 'Finolex Cables',
        vendor_gstin: '08AABCF3456Y1ZX',
        vendor_address: 'Finolex Industries, Pune',
        vendor_email: 'cables@finolex.com',
        payment_term: 'Net 30',
        department: 'Maintenance',
        group_head: 'Tools',
        item_name: 'Spanner Set',
    },
];

// ─── MASTER (item master for dropdowns) ───
export const dummyMaster: any[] = [
    {
        id: 1,
        department: 'Electrical',
        create_group_head: 'Electrical',
        group_head: 'Electrical',
        item_name: 'LED Bulb 20W',
        inventory_status: 'Show',
    },
    {
        id: 2,
        department: 'Electrical',
        create_group_head: 'Electrical',
        group_head: 'Electrical',
        item_name: 'MCB 32A',
        inventory_status: 'Show',
    },
    {
        id: 3,
        department: 'Electrical',
        create_group_head: 'Electrical',
        group_head: 'Electrical',
        item_name: 'Cable 4 Sq mm',
        inventory_status: 'Show',
    },
    {
        id: 4,
        department: 'Electrical',
        create_group_head: 'Electrical',
        group_head: 'Electrical',
        item_name: 'Contactor 25A',
        inventory_status: 'Show',
    },
    {
        id: 5,
        department: 'Production',
        create_group_head: 'Mechanical',
        group_head: 'Mechanical',
        item_name: 'Bearing 6205',
        inventory_status: 'Show',
    },
    {
        id: 6,
        department: 'Production',
        create_group_head: 'Mechanical',
        group_head: 'Mechanical',
        item_name: 'Bearing 6206',
        inventory_status: 'Show',
    },
    {
        id: 7,
        department: 'Production',
        create_group_head: 'Mechanical',
        group_head: 'Mechanical',
        item_name: 'V-Belt B60',
        inventory_status: 'Show',
    },
    {
        id: 8,
        department: 'Maintenance',
        create_group_head: 'Piping',
        group_head: 'Piping',
        item_name: 'GI Pipe 1 inch',
        inventory_status: 'Show',
    },
    {
        id: 9,
        department: 'Maintenance',
        create_group_head: 'Piping',
        group_head: 'Piping',
        item_name: 'PVC Pipe 2 inch',
        inventory_status: 'Show',
    },
    {
        id: 10,
        department: 'Production',
        create_group_head: 'Consumables',
        group_head: 'Consumables',
        item_name: 'Welding Rod 3.15mm',
        inventory_status: 'Show',
    },
    {
        id: 11,
        department: 'Production',
        create_group_head: 'Consumables',
        group_head: 'Consumables',
        item_name: 'Cutting Disc 4 inch',
        inventory_status: 'Show',
    },
    {
        id: 12,
        department: 'Maintenance',
        create_group_head: 'Tools',
        group_head: 'Tools',
        item_name: 'Drill Bit Set HSS',
        inventory_status: 'Show',
    },
    {
        id: 13,
        department: 'Maintenance',
        create_group_head: 'Tools',
        group_head: 'Tools',
        item_name: 'Spanner Set',
        inventory_status: 'Show',
    },
];

// ─── QUOTATION HISTORY ───
export const dummyQuotationHistory: any[] = [];

// ─── MUTABLE DATA STORE ───
// This is the "database" — all CRUD operations work on these arrays.
let _nextId = 100;
export function getNextId() {
    return ++_nextId;
}

export const dataStore = {
    indent: dummyIndents,
    received: dummyReceived,
    po_master: dummyPoMaster,
    inventory: dummyInventory,
    master_data: dummyMasterData,
    master: dummyMaster,
    user_access_master: dummyUsers,
    quotation_history: dummyQuotationHistory,
};
